export const hotNewsCards = [
    {
        title: 'BREAKING NEWS',
        content: '120 injuries in the last month. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?space',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Another incident reported. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?galaxy',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Alien sightings increase. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?star',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Mysterious signals detected. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?sun',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Unexpected weather changes. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?moon',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Strange artifacts found. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?space',
    },
    {
        title: 'BREAKING NEWS',
        content: 'Community on high alert. Nulla interdum sollicitudin justo eget facilisis.',
        buttonText: 'Read more',
        imageUrl: 'https://picsum.photos/600/400?neptune',
    },
];


export const warningCards = [
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',
    'ALIEN IN AREA. Nulla interdum sollicitudin justo eget facilisis.',
    'Further reports of unusual activity.',
    'Maintain vigilance at all times.',
    'Report any suspicious activity immediately.',
    'Avoid traveling alone at night.',
    'Secure all entry points to your home.',
    'Keep emergency contacts on speed dial.',
    'Stay informed through official channels.',
    'Participate in community watch programs.',
    'Ensure your safety plan is up-to-date.',

];

export const contactCardContent = "For any emergency, please contact us at contact@orbitguardians.com.";
